### ISSUE TITLE
--- Revisar as validações---

### ISSUE THREAD

**Issue by joaofranca1993** [joaofranca1993/rent-a-thing#4]
- <FUNCIONARIO>campo Configurar para que datas como nascimento sejam menores que 16 anos, cosiderando que são funcionarios - **IMPLEMENTADO**
- <FUNCIONARIO> campo Matricula implementar funcao para não haver repetição **IMPLEMENTADO**
- <FUNCIONARIO> campo Senha só deve aceitar somente 4 caracteres ou mais. Dar um ignoreCase na hora da comparação, disable case sensitive **IMPLEMENTADO**
 - <FUNCIONARIO> campo Salario so aceitar acima de 400 reais e somente numeros, dando um alert dos erros **IMPLEMENTADO**
- <EQUIPAMENTOS> data aquisição não pode ser maior que a data atual IMPLEMENTADO
- <EQUIPAMENTOS> custo da diária não pode ser maior que 100  **IMPLEMENTADO**
- <RESERVAR> Não permitir que a data inicial seja maior ou igual que a data final. Não permitir que a data inicial seja menor que a data atual **IMPLEMENTADO**
-  <RESERVAR> já citei, mas esses campos não estão sendo limpos após inserção. **IMPLEMENTADO**
- <RELATÓRIO> não está funcionando **CORRIGIDO**
- <RELATÓRIO> implementar um algoritmo que mostre ou oculte os campos de inserções conforme o tipo de relatório escolhido **IMPLEMENTADO**
- <RELATÓRIO> limpar os campos após inserção **IMPLEMENTADO**
- deixar no rodapé de cada janela, o nome do usuário e a ~~data atual (já tem no windows não?)~~. **EM PROGRESSO**

- <RELATÓRIO> dar ingore case nos relatórios **IMPLEMENTADO**
- <RELATÓRIO> funções do relatório não está funcionando, inclusive o último select que é o select do grupo **IMPLEMENTADO**

**Comment by vinimtex** [comment]
Lista atualizada

-     custo da diária não pode ser maior que 100
-     Não permitir que a data inicial seja maior ou igual que a data final. Não permitir que a data inicial seja menor que a data atual
-     Não permitir que a data final seja maior que 7 ????? é de se pensar.
-     já citei, mas esses campos não estão sendo limpos após inserção.
-     <RELATÓRIO> não está funcionando
-     <RELATÓRIO> implementar um algoritmo que mostre ou oculte os campos de inserções conforme o tipo de relatório escolhido
-     <RELATÓRIO> limpar os campos após inserção
-     deixar no rodapé de cada janela, o nome do usuário e a data atual.
